<a href="https://colab.research.google.com/github/anissateyeb/GoMyCode/blob/main/bonus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
def array_operations():
  import numpy as np
  T1=np.array([[1,2],[3,4]], dtype=np.float64)
  T2=np.array([[5,6],[0,8]], dtype=np.float64)
  print(T1)
  print(T2)
  A=T1+T2
  B=T2-T1
  C=T1*T2
  moy=format(sum(sum(T1))/len(T1), '.2f')
  max=np.max(T2)
  print(np.size(T1))
  Taille1=np.size(T1)
  Taille2=np.size(T2)
  #D= np.zeros(Taille1, Taille2)
  for i in range(Taille1):
    for j in range(Taille2):
      if j==0:
        D=0
      else:
        D= T1/T2
  return A,B,C,D ,moy, max
print(array_operations())


[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [0. 8.]]
4
(array([[ 6.,  8.],
       [ 3., 12.]]), array([[ 4.,  4.],
       [-3.,  4.]]), array([[ 5., 12.],
       [ 0., 32.]]), array([[0.2       , 0.33333333],
       [       inf, 0.5       ]]), '5.00', 8.0)


<ipython-input-12-05889ec86420>:21: RuntimeWarning: divide by zero encountered in true_divide
  D= T1/T2
